version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  # - package-ecosystem: "pub" # See documentation for possible values
    # directory: "/sport-log-client/" # Location of package manifests
    # schedule:
      # interval: "daily"
    # target-branch: "develop"