name: Flutter

permissions:
  contents: read
  checks: write

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  format:
    name: format
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
    - name: dart format
      run: dart format --set-exit-if-changed .

  analyze:
    name: analize
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
    - name: flutter pub get
      run: flutter pub get
    - name: flutter analyze
      run: flutter analyze

  build-web:
    name: build web
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
    - name: flutter build web
      run: flutter build web --release

  build-linux:
    name: build linux
    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
    - name: install linux dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
        sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
    - name: flutter build linux
      run: flutter build linux --release
