name: GH-Pages

on:
  push:
    branches: 
      - gh-pages

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: deploy

    permissions:
      contents: read
      pages: write    
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: flutter build web
        run: flutter build web --release --base-href /gear-list-planner/
      - name: configure pages
        uses: actions/configure-pages@v4
      - name: upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build/web
      - name: deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@v2 